- project:
    merge-mode: squash-merge
    default-branch: main
    templates:
      - api-ref-jobs
      - umn-jobs
    check:
      jobs:
        - otc-tox-pep8
    gate:
      jobs:
        - otc-tox-pep8
